

spring:
  profiles:
    active: local
  datasource:
    username: ${DB_USER_ID}
    password: ${DB_USER_PASSWORD}
    url: jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      format_sql: true
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER # Swagger-ui
  logging:
    config: classpath:logback-spring.xml
jwt:
  header: Bearer
  secret: ${JWT_SECRET}
  #hs256 algorithm
sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET_KEY}
    callback:
      url: ${GOOGLE_CALLBACK_URL}
    token:
      url: https://oauth2.googleapis.com/token
fcm:
  projectId: ${PROJECT_ID}
  url: ${API_URL}
  config: ${FCM_CONFIG}